fragment PizzasCatalogResponseFragment on PizzasResponse {
    reason
    success
    catalog {
        description
        id
        name
        img
        ingredients {
            name
            img
            cost
        }
        sizes {
            price,
            name
        }
    }
}