query getPizzasCatalog {
    getPizzasCatalog {
        catalog{
            description
            id
            img
            ingredients{
                name
            }
            name
            sizes{
                name
                price
            }
            toppings{
                cost
                img
                name
            }
        }
    }
}